apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
