apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
