apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sample
    repoURL: https://github.com/ryu-sato/argo-sample.git
    targetRevision: master
  syncPolicy:
    automated: {}
