apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo
  namespace: argocd
spec:
  description: argo関連アプリケーション
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/ryu-sato/argo-sample.git
