apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.3
resources:
- appproject-default.yaml
- appproject-argo.yaml
- application-argocd.yaml
- application-sample.yaml
